name: Integration Tests (MLOps.NET.SQLServer)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests-sql-server:
    runs-on: ubuntu-latest

    services:
      sqlserver: 
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: MLOps4TheWin!
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Install dependencies
      run: dotnet restore MLOps.NET.sln
    - name: Build
      run: dotnet build MLOps.NET.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=IntegrationTestSqlServer            

    
