name: Integration Tests (MLOps.NET.AWS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests-aws:
    runs-on: ubuntu-latest

    services:
      azure: 
        image: adobe/s3mock
        ports:
          - 9090:9090
          - 9191:9191

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Install dependencies
      run: dotnet restore MLOps.NET.sln
    - name: Build
      run: dotnet build MLOps.NET.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=IntegrationTestsAWS            

    
